backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "artists" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artist" # Used in the UI, ie.: "New Post"
    folder: "site/content/artists" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "This is what will show up in the url. eg truelovetattooks.com/artists/TITLE",
        }
      - { label: "First Name", name: "firstName", widget: "string" }
      - { label: "Last Name", name: "lastName", widget: "string" }
      - { label: "Individual Profile Image", name: "imageProfile", widget: "image", required: true }
      - { label: "Color Homepage Image", name: "imageColor", widget: "image", required: true }
      - { label: "B&W Homepage Image", name: "imageBw", widget: "image", required: true }

      - {
          label: "Position",
          name: "position",
          widget: "select",
          options:
            [
              "Tattooer",
              "Piercer",
              "Tattoo Apprentice",
              "Piercing Apprentice",
              "Tattooer/Owner",
            ],
        }
      - {
          label: "Social",
          name: social,
          widget: list,
          max: 2,
          fields:
            [
              {
                label: "Type",
                name: "type",
                widget: select,
                options: ["icons-facebook", "icons-instagram"],
              },
              { label: "Link", name: "link", widget: string },
            ],
        }
      - {
          label: "Bio",
          name: bio,
          widget: object,

          fields:
            [
              {
                label: "Type",
                name: "type",
                widget: select,
                options: ["Tattooing", "Piercing", "Tattooing and Piercing"],
              },

              {
                label: "Since",
                name: "since",
                widget: number,
                value_type: "int",
              },
              { label: "Inspired", name: "inspired", widget: text },
              { label: "Specializes", name: "specializes", widget: text },
              { label: "First Tattoo", name: "firstTattoo", widget: text },
              { label: "Outside", name: "outside", widget: text },
            ],
        }
      # - { label: "Intro Blurb", name: "description", widget: "text" }
      # - { label: "Image", name: "image", widget: "image", required: false }
      # - { label: "Body", name: "body", widget: "markdown" }
      # - {
      #     label: "Tattoos",
      #     name: tattoos,
      #     widget: list,
      #     fields: [{ label: "Test", name: "test", widget: "markdown" }],
      #   }
  #   {
  #   label: "Social Item",
  #   name: item,
  #   widget: object,
  #   fields:
  #     [
  #       { label: "Type", name: "type", widget: string },
  #       { label: "Link", name: "link", widget: string },

  #     ],
  # }

  - name: "pages"
    label: "Main Page"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          
          - {
              label: "About True Love",
              name: blurb,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - { label: Parallax Image 1, name: parallax1, widget: image }
            
          # - {
          #     label: "Intro",
          #     name: intro,
          #     widget: object,
          #     fields:
          #       [
          #         { label: "Heading", name: "heading", widget: string },
          #         { label: "Text", name: "text", widget: "text" },
          #       ],
          #   }
          # - {
          #     label: "Products",
          #     name: products,
          #     widget: list,
          #     fields:
          #       [
          #         { label: "Image", name: "image", widget: "image" },
          #         { label: "Text", name: "text", widget: "text" },
          #       ],
          #   }
          # - {
          #     label: "Values",
          #     name: "values",
          #     widget: "object",
          #     fields:
          #       [
          #         { label: "Heading", name: "heading", widget: string },
          #         { label: "Text", name: "text", widget: "text" },
          #       ],
          #   }
